name: Build
on: push
  # push:
  #   branches: master

jobs:
  json:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: brew info --json
      run: |
        rm -rf Info
        mkdir -p Info
        cd Formula
        for formula in *.rb; do
          brew info --json "$formula" | jq '.[0]? // .' > ../Info/${formula/%rb/json}
        done

    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: 'Generated formula JSON: `brew info --json <formula>`'
        file_pattern: Info
